name: codex

networks:
  codex:
  traefik:
    name: traefik
    external: true

volumes:
  postgres_data:
  postgres_config:

services:
  migrations:
    image: codex:local
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db_pg:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - codex
    restart: "no"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        ENVIRONMENT: dev
    image: codex:local
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      db_pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: on-failure
    volumes:
      - .:/app
    networks:
      - traefik
      - codex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codex.rule=Host(`codex.localhost`)"
      - "traefik.http.routers.codex.entrypoints=web"

  db_pg:
    image: postgres:18-alpine
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES__DB?POSTGRES__DB is required}
      POSTGRES_USER: ${POSTGRES__USER?POSTGRES__USER is required}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD?POSTGRES__PASSWORD is required}
    ports:
      - 9879:${POSTGRES__PORT?POSTGRES__PORT is required}
    networks:
      - codex
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s
    volumes:
      - postgres_data:/var/lib/postgresql
      - postgres_config:/etc/postgresql
