"""Add fieals to sprite model

Revision ID: 7eb533017e10
Revises: 
Create Date: 2026-09-29 13:44:36.318589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb533017e10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('type', sa.Enum('emotion', 'outfit_style', 'location', 'time_of_day', 'archetype', name='tagtype'), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'slug')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index('ix_tags_type', 'tags', ['type'], unique=False)
    op.create_table('universes',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_universes_id'), 'universes', ['id'], unique=False)
    op.create_table('backgrounds',
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('asset_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_id', 'slug')
    )
    op.create_index(op.f('ix_backgrounds_id'), 'backgrounds', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('speech_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_id', 'slug')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('background_tags',
    sa.Column('backgrounds_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backgrounds_id'], ['backgrounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('backgrounds_id', 'tag_id')
    )
    op.create_table('character_tags',
    sa.Column('characters_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('characters_id', 'tag_id')
    )
    op.create_table('sprites',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('asset_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'slug')
    )
    op.create_index(op.f('ix_sprites_id'), 'sprites', ['id'], unique=False)
    op.create_table('emotions',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sprite_id', 'slug')
    )
    op.create_index(op.f('ix_emotions_id'), 'emotions', ['id'], unique=False)
    op.create_table('outfits',
    sa.Column('sprite_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sprite_id'], ['sprites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sprite_id', 'slug')
    )
    op.create_index(op.f('ix_outfits_id'), 'outfits', ['id'], unique=False)
    op.create_table('sprite_tags',
    sa.Column('sprites_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sprites_id'], ['sprites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sprites_id', 'tag_id')
    )
    op.create_table('emotion_tags',
    sa.Column('emotions_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emotions_id'], ['emotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('emotions_id', 'tag_id')
    )
    op.create_table('outfit_tags',
    sa.Column('outfits_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outfits_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outfits_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_tags')
    op.drop_table('emotion_tags')
    op.drop_table('sprite_tags')
    op.drop_index(op.f('ix_outfits_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_emotions_id'), table_name='emotions')
    op.drop_table('emotions')
    op.drop_index(op.f('ix_sprites_id'), table_name='sprites')
    op.drop_table('sprites')
    op.drop_table('character_tags')
    op.drop_table('background_tags')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_backgrounds_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    op.drop_index(op.f('ix_universes_id'), table_name='universes')
    op.drop_table('universes')
    op.drop_index('ix_tags_type', table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
