"""Add description to sprite

Revision ID: 54fbe6ddff24
Revises: 7eb533017e10
Create Date: 2026-09-29 15:18:09.187501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fbe6ddff24'
down_revision: Union[str, Sequence[str], None] = '7eb533017e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен для уже существующих спрайтов, потом убираем его
    op.add_column('sprites', sa.Column('description', sa.Text(), nullable=False, server_default=''))
    op.alter_column('sprites', 'description', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprites', 'description')
    # ### end Alembic commands ###
